class ApplicationController < ActionController::Base
 
    #Railos has a set of rules whenever we communicate with route. 
		#They use csrf token it is generated by the system. 
		#Generated by secret key value, checks to see if user is a real user and not a hijacker. 

		#Use curl command to create a post request to our own api to check if it is working.
		#curl --header "Content-Type: application/json" --request POST --data '{"user": {"email": "l2albert@aplusclaims.com", "password" :"abcd"}}' "http://localhost:3000/sessions"
    skip_before_action :verify_authenticity_token
end
